#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

# Check if the correct number of parameters is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
path_to_file=$1
ip=$2
username=$3
ssh_key=$4

# Transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip":~/ 

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "File transfer failed!"
fi
