#!/usr/bin/env bash

# Update package repository
sudo apt-get -y update

# Install nginx web server
sudo apt-get -y install nginx

# Create the HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Start the nginx service
sudo service nginx start
