#!/usr/bin/env bash

# Update package repository
sudo apt-get -y update

# Install nginx web server
sudo apt-get -y install nginx

# Create the HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Start the nginx service
sudo service nginx start

# Ensure nginx is configured to listen on port 80
sudo sed -i 's/^\(listen [::]:80;\)/\1 default_server;/' /etc/nginx/sites-available/default

# Restart nginx without using systemctl
sudo kill -s HUP $(pidof nginx)
