#!/usr/bin/env bash

# Update package repository
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure Nginx for redirection
sed -i '/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
