#!/usr/bin/env bash

# Update package repository
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Change default content
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create a simple HTML file for the custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx for redirection and custom 404 page
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

# Output new content
echo "Hello World!"
