#!/usr/bin/env bash

PIDFILE=/var/run/my_process.pid

start() {
    if [ -f "$PIDFILE" ]; then
        echo "manage_my_process is already running."
    else
        ./manage_my_process &
        echo "$!" > "$PIDFILE"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        if ps -p "$pid" > /dev/null; then
            sudo kill "$pid"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        rm -f "$PIDFILE"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
