#!/usr/bin/env bash

start_process() {
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop_process() {
    kill "$(pgrep -f /manage_my_process)"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

if [ "$1" == "start" ]; then
    start_process
elif [ "$1" == "stop" ]; then
    stop_process
elif [ "$1" == "restart" ]; then
    restart_process
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
