#!/usr/bin/env bash
# Install ufw and block all incoming except 22, 443, 80

sudo apt-get -y update
sudo apt install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
# configure firewall for 80, 443 and 22
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# enable ufw
sudo ufw enable
sudo ufw status verbose
