#!/usr/bin/env bash
# Run nginx as the nginx user

# Stop Apache processes
pkill apache2

if grep -q "listen 80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
fi


if grep -q "listen \[::\]:80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
fi

chown www-data:www-data /etc/nginx/nginx.conf

chmod 644 /etc/nginx/nginx.conf

service nginx start
