#!/usr/bin/env bash

# Run nginx as nginx user instead of root
# Script that starts nginx as nginx user

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Permissions of the config file
chmod 644 /etc/nginx/nginx.conf

# Listen to port 8080
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
