#!/usr/bin/env bash
# Creates an RSA key pair

#KEY_NAME="school"
#KEY_PASS="betty"
#KEY_BITS="4096"
#ssh-keygen -b $KEY_BITS -N $KEY_PASS -f $KEY_NAME

ssh-keygen -t rsa -f school -b 4096 -N betty
